language: "C"
seedFolders:
  - path: "gcc/test_data/gcc-13.1.0-seeds"
    fileExtentions: [".c"]

programsUnderTest:
  - command: "llvm/test_data/llvm-19.1.6-install/bin/clang"
    flagsToTest:
      - flags: ["-x", "c", "-std=c2x", "-c"]
    versionFlags:
      flags: ["-v"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.c.ClangCrashDetector"
