language: "C"
seedFolders:
  - path: "gcc/test_data/gcc-13.1.0-seeds"
    fileExtentions: [".c"]

programsUnderTest:
  - command: "gcc/test_data/gcc-13.1.0-install/bin/gcc"
    flagsToTest:
      - flags: ["-x", "c", "-std=c2x", "-c"]
    versionFlags:
      flags: ["-v"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.c.GccCrashDetector"
